import fs from 'node:fs/promises';
import path from 'node:path';

import type { DiscoveredWorkspace } from '../runtime/workspace-discovery.js';

/**
 * AGENTS.md generation per `.dev/specs/CLI_INSTALLER.md` §6.
 *
 * Rule: never overwrite an existing `AGENTS.md`. If one is present, drop the
 * managed agent guide under `.seevee/agent/README.md` instead and let the
 * command surface that decision.
 */

export interface AgentFileResult {
  createdTopLevel: boolean;
  readmePath: string;
  agentDirPath: string;
}

export const AGENT_GUIDE = `# Seevee workspace guide for agents

This file is generated by \`seevee init\`. Edit it freely — the CLI will never
overwrite your changes. The canonical schema and reference material live in
the Seevee workspace-agent at \`.seevee/agent/seevee-workspace-agent/\`.

## Canonical entry points

- \`seevee.json\` — workspace document (active CV/presentation, resources,
  policy). Reads/writes must respect the schema's \`strict()\` rules.
- \`cvs/<id>.json\` — canonical CV documents (envelope type
  \`seevee.cv\`). Every CV has an \`id\`, \`schemaVersion\`, and stable entity
  IDs referenced by comments and provenance.
- \`provenance/<cv-id>.json\` — sources and assertions backing each CV.
- \`comments/<cv-id>.json\` — threads attached to CV fields/render bindings.
- \`presentations/<id>.json\` — presentation config (template/version,
  page profile, tokens).
- \`templates/local/\` — user-owned template source. The dashboard reads
  only what you reference from a presentation.

## Editing rules

1. Compute every change into a temporary sibling file (for example
   \`cvs/main.json.tmp\`) and rename atomically. The dashboard watches
   canonical paths and rejects half-written files.
2. Use stable, human-readable IDs (\`work-acme-senior\`, \`skill-typescript\`)
   for any entity an agent might need to reference. Random IDs break the
   comments/provenance link.
3. Do not introduce new top-level keys in CV, workspace, presentation or
   comments documents — schemas are \`strict()\`. Use the \`extensions\`
   object for vendor-/user-defined metadata.
4. Run \`seevee validate\` after editing. Fix every reported issue before
   expecting the dashboard to publish the new revision.

## A4 render rules

- Page profile \`A4 portrait\` is the default; tokens in
  \`presentations/<id>.json\` override per-presentation.
- Sections must never exceed the configured \`pagination\` budget. Split
  bullets before inventing new entities.
- Render bindings (overflow, truncation) live on the presentation, never
  on the CV.

## Comments workflow

- Threads attach via \`target\` selectors (\`node\`, \`field\`, \`section\`,
  \`text-quote\`, \`render-binding\`, \`page-region\`). Match the exact
  resource revision or the comment is dismissed.
- Resolutions must be deterministic and explainable; deterministic
  comments may be auto-resolved via \`workspace.policy.autoResolveDeterministicComments\`.

## Validation

\`\`\`sh
seevee validate                          # validate every canonical resource
seevee validate --json                   # machine-readable
seevee doctor                            # workspace + runtime health
\`\`\`

## Where to read more

Point your agent at \`.seevee/agent/seevee-workspace-agent/\` for the
canonical Seevee workspace-agent skill. The dashboard will surface
additional context as the workspace grows.
`;

export const AGENT_README_HEADER = `# Seevee workspace-agent

This directory is managed by \`seevee init\`. The CLI installs the
Seevee workspace-agent skill here so any coding agent can discover it
without external setup.

## What's in here

- \`seevee-workspace-agent/\` — the canonical Seevee workspace-agent skill.
  Agents read it for full workflow context; the user-facing dashboard does
  not depend on it.

Agents should read this directory and the workspace root's \`AGENTS.md\`
together before editing canonical resources.
`;

export async function writeAgentFiles(
  ws: DiscoveredWorkspace,
  options: { allowOverwrite?: boolean } = {},
): Promise<AgentFileResult> {
  const allowOverwrite = options.allowOverwrite === true;
  const createdTopLevel = !!(await writeIfMissing(path.join(ws.root, 'AGENTS.md'), AGENT_GUIDE, allowOverwrite));

  const agentDir = path.join(ws.runtimeDir, 'agent');
  await fs.mkdir(agentDir, { recursive: true });
  const readme = path.join(agentDir, 'README.md');
  await writeAtomic(readme, AGENT_README_HEADER);
  await fs.mkdir(path.join(agentDir, 'seevee-workspace-agent'), { recursive: true });

  return {
    createdTopLevel,
    readmePath: readme,
    agentDirPath: agentDir,
  };
}

async function writeIfMissing(file: string, content: string, allowOverwrite: boolean): Promise<boolean> {
  if (!allowOverwrite) {
    try {
      await fs.access(file);
      return false;
    } catch {
      // file doesn't exist — proceed
    }
  }
  await writeAtomic(file, content);
  return true;
}

async function writeAtomic(file: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  const tmp = `${file}.tmp-${process.pid}-${Date.now()}`;
  await fs.writeFile(tmp, content, 'utf8');
  await fs.rename(tmp, file);
}
