import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import type { DiscoveredWorkspace } from '../runtime/workspace-discovery.js';

/**
 * AGENTS.md generation per `.dev/specs/CLI_INSTALLER.md` §6.
 *
 * Rule: never overwrite an existing `AGENTS.md`. If one is present, drop the
 * managed agent guide under `.seevee/agent/README.md` instead and let the
 * command surface that decision.
 */

export interface AgentFileResult {
  createdTopLevel: boolean;
  readmePath: string;
  agentDirPath: string;
}

export const AGENT_GUIDE = `# Seevee workspace guide for agents

This file is generated by \`seevee init\`. Edit it freely — the CLI will never
overwrite your changes. The canonical schema and reference material live in
the Seevee workspace-agent at \`.seevee/agent/seevee-workspace-agent/\`.

## Canonical entry points

- \`seevee.json\` — workspace document (active CV/presentation, resources,
  policy). Reads/writes must respect the schema's \`strict()\` rules.
- \`cvs/<id>.json\` — canonical CV documents (envelope type
  \`seevee.cv\`). Every CV has an \`id\`, \`schemaVersion\`, and stable entity
  IDs referenced by comments and provenance.
- \`provenance/<cv-id>.json\` — sources and assertions backing each CV.
- \`comments/<cv-id>.json\` — threads attached to CV fields/render bindings.
- \`presentations/<id>.json\` — presentation config (template/version,
  page profile, tokens).
- \`templates/local/\` — user-owned template source. The dashboard reads
  only what you reference from a presentation.
- \`seevee init\` installs the styled Classic Astro template and registers
  it as the default presentation for a new CV workspace.

## Editing rules

1. Compute every change into a temporary sibling file (for example
   \`cvs/main.json.tmp\`) and rename atomically. The dashboard watches
   canonical paths and rejects half-written files.
2. Use stable, human-readable IDs (\`work-acme-senior\`, \`skill-typescript\`)
   for any entity an agent might need to reference. Random IDs break the
   comments/provenance link.
3. Do not introduce new top-level keys in CV, workspace, presentation or
   comments documents — schemas are \`strict()\`. Use the \`extensions\`
   object for vendor-/user-defined metadata.
4. Run \`seevee validate\` after editing. Fix every reported issue before
   expecting the dashboard to publish the new revision.

## A4 render rules

- Page profile \`A4 portrait\` is the default; tokens in
  \`presentations/<id>.json\` override per-presentation.
- Sections must never exceed the configured \`pagination\` budget. Split
  bullets before inventing new entities.
- Render bindings (overflow, truncation) live on the presentation, never
  on the CV.
- Creating a CV is not complete with JSON alone. Create/register its
  presentation and give it a finished visual design. Use the installed
  Classic template only when the user has not provided a visual direction.
- The user controls the CV's visual layout. Build custom Astro/CSS when
  useful: CSS Grid, Flexbox, multiple columns, sidebars, asymmetry, and
  other layouts are all allowed. Put each template's dashboard preview
  styles in its own \`styles/dashboard.css\`; the Studio scopes that file to
  the CV canvas. Keep print rules in \`styles/print.css\`, and never edit the
  Studio dashboard stylesheet to style a CV. The bundled templates and
  dashboard style controls are starting points, not constraints. Keep
  semantic bindings, selected page sizing, accessibility, and export safety
  intact.
- Treat the CV as a static document that will be printed/exported to PDF.
  Never add scrollable CV regions (including \`overflow: auto/scroll\`,
  fixed-height panels, or nested scrolling), editor controls, or content that
  requires clicks, scripts, hover, or focus to appear. Keep all information
  visible in the document and let it paginate across the selected page size.
  These rules apply to CV/template output, not dashboard shell controls.

## Comments workflow

- Threads attach via \`target\` selectors (\`node\`, \`field\`, \`section\`,
  \`text-quote\`, \`render-binding\`, \`page-region\`). Match the exact
  resource revision or the comment is dismissed.
- Resolutions must be deterministic and explainable; deterministic
  comments may be auto-resolved via \`workspace.policy.autoResolveDeterministicComments\`.

## Dashboard and comment pins

- Start or reopen the local dashboard with \`seevee start\`; use \`seevee open\` to open it, \`seevee status\` to find its URL, and \`seevee stop\` to stop it cleanly.
- Read the registered comments resource for the selected CV, finding it by matching its \`cvId\` in \`seevee.json\`. Follow \`data.threadOrder\` and use the latest message in each thread's \`messageOrder\`.
- Dashboard comments put the strongest semantic selector (\`FieldSelector\`, \`NodeSelector\`, or \`SectionSelector\`) before the \`PageRegionSelector\` visual fallback. The \`seevee.placement\` extension records a readable element label, a short snapshot of visible text, and normalized page coordinates. Resolve stable IDs against the current CV first; treat the saved text and page location as clues if revisions have changed.
- Dashboard-created comments default to category \`general\` and priority \`normal\`; classify the requested work from its message. If the latest message does not say what should change, ask rather than guessing.
- Keep comments open until the requested change is made and validated. Do not resolve a thread just because it was read or attempted.

## Validation

\`\`\`sh
seevee validate                          # validate every canonical resource
seevee validate --json                   # machine-readable
seevee doctor                            # workspace + runtime health
\`\`\`

## Where to read more

Point your agent at \`.seevee/agent/seevee-workspace-agent/\` for the
canonical Seevee workspace-agent skill. The dashboard will surface
additional context as the workspace grows.
`;

export const AGENT_README_HEADER = `# Seevee workspace-agent

This directory is managed by \`seevee init\`. The CLI installs the
Seevee workspace-agent skill here so any coding agent can discover it
without external setup.

## What's in here

- \`seevee-workspace-agent/\` — the canonical Seevee workspace-agent skill.
  Agents read it for full workflow context; the user-facing dashboard does
  not depend on it.

Agents should read this directory and the workspace root's \`AGENTS.md\`
together before editing canonical resources.
`;

export async function writeAgentFiles(
  ws: DiscoveredWorkspace,
  options: { allowOverwrite?: boolean } = {},
): Promise<AgentFileResult> {
  const allowOverwrite = options.allowOverwrite === true;
  const createdTopLevel = !!(await writeIfMissing(path.join(ws.root, 'AGENTS.md'), AGENT_GUIDE, allowOverwrite));

  const agentDir = path.join(ws.runtimeDir, 'agent');
  await fs.mkdir(agentDir, { recursive: true });
  const readme = path.join(agentDir, 'README.md');
  await writeAtomic(readme, AGENT_README_HEADER);
  const skillTarget = path.join(agentDir, 'seevee-workspace-agent');
  const skillSource = await findAgentSkillSource();
  await fs.mkdir(skillTarget, { recursive: true });
  await fs.cp(skillSource, skillTarget, { recursive: true, force: true });

  return {
    createdTopLevel,
    readmePath: readme,
    agentDirPath: agentDir,
  };
}

async function findAgentSkillSource(): Promise<string> {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    process.env['SEEVEE_AGENT_SKILL_DIR'],
    path.resolve(here, '../../../agent/seevee-workspace-agent'),
    path.resolve(here, '../../../../skills/seevee-workspace-agent'),
  ].filter((candidate): candidate is string => Boolean(candidate));
  for (const candidate of candidates) {
    try {
      if ((await fs.stat(path.join(candidate, 'SKILL.md'))).isFile()) return candidate;
    } catch {
      // Try the source-tree or bundled runtime location next.
    }
  }
  throw new Error('Seevee workspace-agent skill is missing from this installation. Reinstall Seevee and run `seevee init` again.');
}

async function writeIfMissing(file: string, content: string, allowOverwrite: boolean): Promise<boolean> {
  if (!allowOverwrite) {
    try {
      await fs.access(file);
      return false;
    } catch {
      // file doesn't exist — proceed
    }
  }
  await writeAtomic(file, content);
  return true;
}

async function writeAtomic(file: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  const tmp = `${file}.tmp-${process.pid}-${Date.now()}`;
  await fs.writeFile(tmp, content, 'utf8');
  await fs.rename(tmp, file);
}
